version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "$PORT:80"
    environment:
      BASE_URL: $BASE_URL
      PORT: $PORT
      TOKEN_SECRET: $TOKEN_SECRET
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_HOST: $DATABASE_HOST
      DATABASE_PORT: $DATABASE_PORT
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      PHP_UPLOAD_MAX_FILESIZE: 20M
      PHP_POST_MAX_SIZE: 25M
    volumes:
      - ./app:/app
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer:latest
    ports:
      - $ADMINER_PORT:8080
    depends_on:
      - db

volumes:
  postgresdata: {}
